givery-bootcamp/dena-2024-team1

- frontend/package-lock.json
- frontend/package.json
- frontend/postcss.config.js
- frontend/src/app/App.scss
- frontend/src/app/App.tsx
- frontend/src/main.scss
- frontend/src/main.tsx
- frontend/tailwind.config.js
スタイリングのためにTailwindCSSを導入します。
一旦トップは適当に↓としてます
TailwindCSSが動作していることを確認してください。
- Closes #18
> TailwindCSSの導入

- frontend/src/app/App.tsx
- frontend/tailwind.config.js
[FigmaのColor](https://www.figma.com/design/nAkyKY6tzb5apCzYllxVfg/Web-App?node-id=13-603&t=D26LA83cBlMQLzm5-4)に合わせて、TailwindCSSのカラーパレットを設定します。
試しにヘッダーに`bg-primary`を指定しています。
カラーパレットが問題なく指定できることを確認してください。
- Closes #21
> カラーパレットの設定

- frontend/src/app/AppRoute.tsx
- frontend/src/pages/PostDetailPage.tsx
- frontend/src/shared/components/Container.tsx
投稿詳細画面のViewを実装します。
APIとの繋ぎ込みは #25 に分割するのでこのPRの責務外です。
- Figma通りのUIであること
- Closes #6
> 投稿詳細画面のView実装

- .github/workflows/eslint.yml
- frontend/src/pages/PostDetailPage.tsx
フロントエンドのCI環境を構築します。
なし
- CIが正常に動くこと
- Closes #17
> フロントエンドのCI環境の構築

- docker-compose.yml
- docker/openapi.Dockerfile
- openapi/openapi.yml
- `docker compose up`したら、ポート3031で開きます。
- ケース1のOASを書きました
- Closes #8
> ケース1のOASを書いた

- backend/internal/controllers/post_controller.go
- backend/internal/entities/post.go
- backend/internal/entities/user.go
- backend/internal/interfaces/post_repository.go
- backend/internal/interfaces/user_repository.go
- backend/internal/middleware/router.go
- backend/internal/repositories/post_repository.go
- backend/internal/repositories/user_repository.go
- backend/internal/usecases/post_usecase.go
投稿一覧の取得APIの作成
[スクリーンショット 2024-05-28 16 44 18](https://github.com/givery-bootcamp/dena-2024-team1/assets/26759036/c44f7582-3ace-4608-bd60-54bd00dcf3d9)
- Closes #9
> 投稿一覧の取得APIの作成

- frontend/eslint.config.js
インデントがルールに沿っていない場合にエラーになるよう設定を追加します。
特になし
- インデントがルールに沿っていない場合にESLintでエラーが出る
- Closes #38
> インデントを揃えるためのESLintルールを追加する

- .gitignore
- .vscode/extensions.json
- .vscode/setting.json
- backend/.golangci.yaml
- backend/internal/controllers/controller_helper.go
- backend/internal/controllers/hello_world_controller.go
- backend/internal/external/mysql.go
- backend/internal/middleware/cors.go
- backend/internal/middleware/router.go
- backend/internal/middleware/transaction.go
- backend/internal/repositories/hello_world_repository.go
- backend/main.go
以下の手順が再現するか
1. このブランチをlocalに持ってくる
2. vscodeの拡張機能をinstall する
3. VSCode上で`cmd + shift + p`でコマンドパレットを開き、「Go: Install/Update Tools」を実行して、ツールすべてをinstallする
4. もし3で「Go: Install/Update Toolsの実行すらできなかったら、localにGolangが入っていないっぽいので入れてください。
5. ここまで終わったら、おそらくgoファイルを保存するたびにlintとformatter がきくはずなので、goファイルを開いて適当な空行入れて保存してみてください
6. formatterがきいてればOK
- Closes #27 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> BEのVSCodeでの開発環境整備

- .github/workflows/deploy.yml
> mainブランチにpushされたときpush stepを走らせる

- frontend/src/shared/components/Button.tsx
- frontend/tailwind.config.js
汎用的なButtonコンポーネントを作成します。
- ButtonコンポーネントがFigma通りのUIになっていること
- PostListPageとかに適当にButtonを配置して確認してください(本当はStorybookとか入れたい)
- Closes #67
> Buttonコンポーネントの作成

- .github/workflows/backend-lint.yml
- backend/internal/entity/post.go
- reviewDogをつかって、PRにlintエラーのコメントを出すように。
- 下に出てるよ
- Closes #77
> CIにバックエンドリンターを追加

- backend/internal/controller/repository/post_repository.go
- frontend/src/features/posts/PostActionButtons.tsx
- frontend/src/pages/PostDetailPage.tsx
- frontend/src/shared/services/API.ts
- PostDeleteAPIの繋ぎ込み
- Closes #88
> PostDeleteAPIの繋ぎ込み

- backend/internal/controller/repository/model/sketch_model.go
- backend/internal/entity/sketch.go
> Sketchモデルの定義

- backend/internal/controller/handler/sketch_handler.go
- backend/internal/controller/repository/sketch_repository.go
- backend/internal/infrastructure/http/router/router.go
- backend/internal/openapi/openapi.gen.go
- backend/internal/registry/registry.go
- backend/internal/usecase/repository/sketch_repository.go
- backend/internal/usecase/sketch_usecase.go
- frontend/src/generated/api.ts
- openapi/openapi.yml
> 画像一覧取得APIの作成

- backend/internal/config/config.go
- backend/internal/controller/handler/sketch_handler.go
- backend/internal/infrastructure/database/mysql.go
- backend/internal/openapi/openapi.gen.go
- frontend/src/generated/api.ts
- mysql/sql/seed.sql
- openapi/openapi.yml
- seedファイルの準備
- SketchesAPIを修正
- docker compose down
- docker compose up
- docker-compose exec db sh -c "mysql training < /sqlscripts/seed.sql"
- GET /sketches で取得できることを確認
- Closes #0
> シートファイルの準備とSketches取得APIの修正

- frontend/package-lock.json
- frontend/package.json
- frontend/src/features/sketches/SketchList/SketchItem.tsx
- frontend/src/features/sketches/SketchList/SketchList.tsx
- frontend/src/pages/SketchListPage.tsx
- frontend/src/shared/components/InfiniteCanvas.tsx
スケッチ一覧画面で上下左右に自由にスクロールできるようにします。
https://denatech.slack.com/archives/C07181G628J/p1719385264473889
**※新たにライブラリを追加したのでローカルで`npm i`を実行してください**
- スケッチ一覧画面で自由にスクロールできること
- 外部ライブラリのコンポーネント化の粒度は適切か https://github.com/givery-bootcamp/dena-2024-team1/pull/136#discussion_r1654260887
- Closes #133
> スケッチ一覧画面のインフィニティキャンバス化

- frontend/src/features/sketches/SketchCreateForm.tsx
- frontend/src/features/sketches/SketchCreateForm/SketchCreateForm.tsx
- frontend/src/features/sketches/SketchCreateForm/index.ts
- frontend/src/features/sketches/SketchCreateForm/useSketchCreateForm.ts
- frontend/src/features/sketches/SketchHandWriter/useSketchHandWriter.ts
- frontend/src/features/sketches/SketchList/SketchItem.tsx
- frontend/src/pages/SketchCreatePage.tsx
- frontend/src/shared/services/API.ts
スケッチアップロードAPIと繋ぎ込みます。
[![Image from Gyazo](https://i.gyazo.com/46b87c8c8bfeeca110afdad42bd6a769.gif)](https://gyazo.com/46b87c8c8bfeeca110afdad42bd6a769)
- スケッチ投稿画面で投稿ボタンを押すと、投稿したスケッチがスケッチ一覧画面に表示される
- Closes #137
> スケッチアップロードAPIとの繋ぎ込み

- .github/workflows/deploy.yml
デプロイのECSの最新のタスク定義を利用する
これにAWS周りの環境変数が設定されているので必須
- Closes #0
> 最新のタスク定義を利用する

- .github/workflows/be-build.yml
- .github/workflows/be-lint.yml
- .github/workflows/deploy.yml
- .github/workflows/fe-build.yml
- .github/workflows/fe-lint.yml
- backend/README.md
- frontend/README.md
- CIでbuildを回すように
- fe
- be
- CI上でbuildが回っていることを確認する
- Closes #148
> CIでbuildを回すように

- frontend/.env.production
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/AuthProvider.tsx
- frontend/src/config/api.ts
- frontend/src/pages/CreatePostPage.tsx
- frontend/src/pages/PostDetailPage.tsx
- frontend/src/pages/SignInPage.tsx
- frontend/src/pages/SignOutPage.tsx
- frontend/src/pages/SignUpPage.tsx
- frontend/src/shared/services/API.ts
本番環境へのリクエストのURLを設定
configファイルを生成し、APIを呼び出す時に、configファイルをインポートして引数にセットしている
- Closes #150
> 本番環境へのリクエスト情報を設定

- frontend/.env.production
- frontend/package.json
- frontend/src/app/AuthProvider.tsx
- frontend/src/config/api.ts
- frontend/src/features/posts/PostEditForm.tsx
- frontend/src/features/sketches/SketchCreateForm/useSketchCreateForm.ts
- frontend/src/pages/CreatePostPage.tsx
- frontend/src/pages/PostDetailPage.tsx
- frontend/src/pages/SignInPage.tsx
- frontend/src/pages/SignOutPage.tsx
- frontend/src/pages/SignUpPage.tsx
- frontend/src/shared/services/API.ts
https://github.com/givery-bootcamp/dena-2024-team1/pull/153
で設定したリクエストでは自動生成されたコンフィグに上書きされてしまっていたので、適切な位置にコンフィグを設定した
設定箇所：https://github.com/givery-bootcamp/dena-2024-team1/pull/157/commits/ad9422d946a0035b56e767a718f86390acf02bd9#diff-f105b7c5ca7816029559979067ec5b7b9888073f883c1d7cc0d28f002c174f9bR7
- Closes
> httpリクエストの設定を適切に行う

- .github/workflows/deploy.yml
- backend/internal/config/config.go
- backend/internal/infrastructure/filestorage/s3.go
> ECS上のAWSの認証情報が間違っていたので、タスクを更新

- backend/internal/controller/handler/user_handler.go
- backend/internal/openapi/openapi.gen.go
- frontend/src/features/posts/PostItem.tsx
- frontend/src/features/sketches/SketchList/SketchItem.tsx
- frontend/src/generated/api.ts
- frontend/src/pages/PostDetailPage.tsx
- frontend/src/pages/SignInPage.tsx
- frontend/src/pages/SignUpPage.tsx
- openapi/openapi.yml
- OASをcamelCase→snakeCaseに
- Closes #0
> OASのスタイルがブレてたので修正: camel→snake

- frontend/src/features/users/UserAuthForm/UserAuthForm.tsx
- frontend/src/shared/components/Form/FormErrorMessage.tsx
- frontend/src/shared/components/Form/FormField.tsx
- frontend/src/shared/components/Form/FormLabel.tsx
- frontend/src/shared/components/Form/index.ts
- frontend/src/shared/components/Input.tsx
フォーム周りのスタイルが重複していたため、再利用性を上げるために汎用的なコンポーネントに分割しました。
UIの変更はありません。
- 分割の粒度は適切か
- フォーム周りのコンポーネントは扱いやすいか
- Closes #152
> フォーム周りの汎用コンポーネントの作成

- frontend/src/pages/SketchListPage.tsx
- frontend/tailwind.config.js
bodyの高さをscreenの高さからヘッダーの高さを引いたものにすることで、スクロール出来ないようにして
モーダルを表示してスクロールした時に、下に余白が表示されないようにした
モーダルを表示して、スクロールしても余白が表示されないか
変数名は適切か
- Closes #166
> モーダルを表示してスクロールしたときに表示される下の空白を削除

- frontend/src/features/sketches/SketchColorPicker.tsx
- frontend/src/features/sketches/SketchCreateForm/SketchCreateForm.tsx
- frontend/src/features/sketches/SketchHandWriter/useSketchHandWriter.ts
- frontend/src/features/sketches/SketchTool.tsx
- frontend/src/pages/SketchCreatePage.tsx
- frontend/src/shared/hooks/useCanvas.ts
- frontend/src/shared/hooks/useColorPicker.ts
スケッチ投稿時に任意の色を指定できるようにします。
- スケッチ投稿時に色を指定して投稿できる
- スケッチ一覧画面に↑の色で描かれたスケッチが表示される
- Closes #184
> 線を任意の色に変えられるようにする
